[package]
name = "collab-code"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
serde = { version = "1.0.218", features = ["derive"] } 
serde_json = "1.0.139"
tokio = { version = "1.43.0", features = ["full"] }
tokio-tungstenite = "0.26.2"
